Added pagination.
jasontaylordev/CleanArchitecture pull request #227
Opened 2020-09-02 19:50 UTC by iayti

I added pagination support using @jbogard's Contoso University sample. I also added detailed response for pagination. I see the #121 @MCCshreyas commit and implement @jasontaylordev  advice. Thank you for your interest. 

Have a nice coding 😃

```csharp
PaginatedList<TodoItemDto> list = await _context.TodoItems
                .Where(x => x.ListId == request.ListId)
                .OrderBy(x => x.Title)
                .ProjectTo<TodoItemDto>(_mapper.ConfigurationProvider)
                .PaginatedListAsync(request.PageNumber, request.PageSize);
````

![Pagination_Sample_Request_Response](https://user-images.githubusercontent.com/30297580/92027608-76e19400-ed6b-11ea-9810-2058951b14ec.jpg)

2020-09-02 22:05 UTC, vksantoshsunny approved these changes

2020-09-03 11:28 UTC, jasontaylordev requested changes
Thanks a lot for the PR, it's looking good so far - please can you make the requested changes?

2020-09-03 11:28 UTC, jasontaylordev commented on src/Application/Common/Models/PaginationQuery.cs
> +}
Recommend dropping pagination query, I'd rather just add the properties directly to the query. That way query can remain isolated from one another and they remain explicit with regards to the input requirements.

2020-09-03 11:28 UTC, jasontaylordev commented on src/Application/Common/Mappings/MappingExtensions.cs
> +    using Models;
Using statements outside namespaces, sorted alphabetically, without line breaks between

2020-09-03 11:28 UTC, jasontaylordev commented on src/Application/Common/Models/PaginationResponse.cs
> +}
This is not required, the PaginationList<T> has the complete details.

2020-09-03 11:54 UTC, iayti commented
> Thanks a lot for the PR, it's looking good so far - please can you make the requested changes?

Thank you for the advice, it became simpler and more beautiful this way. 😃

2020-09-03 12:58 UTC, merged